-- @param unique_id STRING
SELECT
  f.unique_id,
  f.name,
  f.organization_type,
  f.facilityTypeId AS facility_type_id,
  f.operatorTypeId AS operator_type_id,
  f.yearEstablished AS year_established,
  f.acceptsVolunteers AS accepts_volunteers,
  f.officialPhone AS official_phone,
  f.phone_numbers,
  f.email,
  f.officialWebsite AS official_website,
  f.websites,
  f.facebookLink AS facebook_link,
  f.address_line1,
  f.address_line2,
  f.address_line3,
  f.address_city,
  f.address_stateOrRegion AS address_state_or_region,
  f.address_zipOrPostcode AS address_zip_or_postcode,
  f.address_country,
  f.address_countryCode AS address_country_code,
  f.latitude,
  f.longitude,
  f.description,
  f.area,
  f.numberDoctors AS number_doctors,
  f.capacity,
  f.specialties,
  f.procedure,
  f.equipment,
  f.capability,
  f.distinct_social_media_presence_count,
  f.post_metrics_most_recent_social_media_post_date,
  f.post_metrics_post_count,
  f.engagement_metrics_n_followers,
  f.engagement_metrics_n_likes,
  f.engagement_metrics_n_engagements,
  lv.website_status,
  lv.website_working_url,
  lv.official_website_url,
  lv.website_error,
  lv.website_http_code,
  lv.facebook_status,
  lv.facebook_url,
  lv.facebook_error,
  lv.facebook_http_code,
  lv.checked_at,
  av.geocode_status AS address_geocode_status,
  av.geocode_provider AS address_geocode_provider,
  av.geocode_formatted_address,
  av.verified_city,
  av.verified_state_or_region,
  av.verified_zip_or_postcode,
  av.mismatch_flags AS address_mismatch_flags,
  av.checked_at AS address_checked_at,
  cv.rule_status AS claim_rule_status,
  cv.rule_score AS claim_rule_score,
  cv.consistency_status AS claim_consistency_status,
  cv.consistency_score AS claim_consistency_score,
  cv.consistency_provider AS claim_consistency_provider,
  cv.consistency_summary AS claim_consistency_summary,
  cv.unsupported_specialties AS claim_unsupported_specialties,
  cv.orphan_claim_terms AS claim_orphan_terms,
  cv.mismatch_flags AS claim_mismatch_flags,
  cv.checked_at AS claim_checked_at
FROM databricks_virtue_foundation_dataset_dais_2026.virtue_foundation_dataset.facilities f
LEFT JOIN workspace.gold.facility_link_validation lv
  ON lv.unique_id = f.unique_id
LEFT JOIN workspace.gold.facility_address_validation av
  ON av.unique_id = f.unique_id
LEFT JOIN workspace.gold.facility_claim_validation cv
  ON cv.unique_id = f.unique_id
WHERE f.unique_id = :unique_id
LIMIT 1;
