// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    facility_cities: {
        name: "facility_cities";
        parameters: {
          /** STRING - use sql.string() */
          country_code: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          zip: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          city: string;
        }>;
      };
    facility_detail: {
        name: "facility_detail";
        parameters: {
          /** STRING - use sql.string() */
          unique_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          organization_type: string;
          /** @sqlType STRING */
          facility_type_id: string;
          /** @sqlType STRING */
          operator_type_id: string;
          /** @sqlType STRING */
          year_established: string;
          /** @sqlType STRING */
          accepts_volunteers: string;
          /** @sqlType STRING */
          official_phone: string;
          /** @sqlType STRING */
          phone_numbers: string;
          /** @sqlType STRING */
          email: string;
          /** @sqlType STRING */
          official_website: string;
          /** @sqlType STRING */
          websites: string;
          /** @sqlType STRING */
          facebook_link: string;
          /** @sqlType STRING */
          address_line1: string;
          /** @sqlType STRING */
          address_line2: string;
          /** @sqlType STRING */
          address_line3: string;
          /** @sqlType STRING */
          address_city: string;
          /** @sqlType STRING */
          address_state_or_region: string;
          /** @sqlType STRING */
          address_zip_or_postcode: string;
          /** @sqlType STRING */
          address_country: string;
          /** @sqlType STRING */
          address_country_code: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType STRING */
          description: string;
          /** @sqlType STRING */
          area: string;
          /** @sqlType STRING */
          number_doctors: string;
          /** @sqlType STRING */
          capacity: string;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType STRING */
          procedure: string;
          /** @sqlType STRING */
          equipment: string;
          /** @sqlType STRING */
          capability: string;
          /** @sqlType STRING */
          distinct_social_media_presence_count: string;
          /** @sqlType STRING */
          post_metrics_most_recent_social_media_post_date: string;
          /** @sqlType STRING */
          post_metrics_post_count: string;
          /** @sqlType STRING */
          engagement_metrics_n_followers: string;
          /** @sqlType STRING */
          engagement_metrics_n_likes: string;
          /** @sqlType STRING */
          engagement_metrics_n_engagements: string;
          /** ok if any URL works; fail if all fail; missing if no URLs */
          website_status: string;
          /** First URL that returned ok */
          website_working_url: string;
          /** First working URL, or officialWebsite normalized if none work */
          official_website_url: string;
          /** Summary when no URL works */
          website_error: string;
          /** HTTP code from first working URL, or last attempted */
          website_http_code: number;
          /** ok | fail | timeout | missing | blocked | error */
          facebook_status: string;
          /** Normalized Facebook URL used for the check */
          facebook_url: string;
          /** Error detail when status is fail/timeout/blocked/error */
          facebook_error: string;
          /** Last HTTP status code, if any */
          facebook_http_code: number;
          /** When this row was last validated */
          checked_at: string;
          /** ok | partial | failed | skipped */
          address_geocode_status: string;
          /** google | nominatim | none */
          address_geocode_provider: string;
          /** Best formatted address from geocoder */
          geocode_formatted_address: string;
          /** Geocoder-resolved city or locality */
          verified_city: string;
          /** Geocoder-resolved state or admin area */
          verified_state_or_region: string;
          /** Geocoder-resolved postal code */
          verified_zip_or_postcode: string;
          /** Comma-separated: city, state, zip, coords */
          address_mismatch_flags: string;
          /** When this row was last validated */
          address_checked_at: string;
          /** ok | weak | mismatch | skipped | skipped_no_claims */
          claim_rule_status: string;
          /** Fraction of specialties with supporting claim keywords (0-1) */
          claim_rule_score: number;
          /** ok | weak | mismatch | skipped | pending */
          claim_consistency_status: string;
          /** Semantic consistency score from AI when run (0-1) */
          claim_consistency_score: number;
          /** rules | openai | none */
          claim_consistency_provider: string;
          /** Short human-readable consistency note */
          claim_consistency_summary: string;
          /** Comma-separated specialty_canonical values without supporting claim text */
          claim_unsupported_specialties: string;
          /** Procedure/capability terms without a matching specialty family */
          claim_orphan_terms: string;
          /** Comma-separated: unsupported_specialties, orphan_claims, semantic_mismatch */
          claim_mismatch_flags: string;
          /** When this row was last validated */
          claim_checked_at: string;
        }>;
      };
    facility_list: {
        name: "facility_list";
        parameters: {
          /** BOOLEAN - use sql.boolean() */
          filter_has_phone: SQLBooleanMarker;
          /** BOOLEAN - use sql.boolean() */
          filter_has_email: SQLBooleanMarker;
          /** BOOLEAN - use sql.boolean() */
          filter_has_working_website: SQLBooleanMarker;
          /** BOOLEAN - use sql.boolean() */
          filter_has_working_facebook: SQLBooleanMarker;
          /** BOOLEAN - use sql.boolean() */
          filter_has_social: SQLBooleanMarker;
          /** STRING - use sql.string() */
          specialty_canonical: SQLStringMarker;
          /** STRING - use sql.string() */
          zip: SQLStringMarker;
          /** STRING - use sql.string() */
          city: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          country_code: SQLStringMarker;
          /** STRING - use sql.string() */
          claim_search: SQLStringMarker;
          /** STRING - use sql.string() */
          claim_search_2: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          facility_type_id: string;
          /** @sqlType STRING */
          operator_type_id: string;
          /** @sqlType STRING */
          year_established: string;
          /** @sqlType STRING */
          procedure: string;
          /** @sqlType STRING */
          equipment: string;
          /** @sqlType STRING */
          capability: string;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType STRING */
          email: string;
          /** @sqlType STRING */
          website: string;
          /** @sqlType STRING */
          official_phone: string;
          /** @sqlType STRING */
          number_doctors: string;
          /** ok if any URL works; fail if all fail; missing if no URLs */
          website_status: string;
          /** ok | fail | timeout | missing | blocked | error */
          facebook_status: string;
          /** @sqlType STRING */
          match_tier: string;
        }>;
      };
    facility_search_by_text: {
        name: "facility_search_by_text";
        parameters: {
          /** STRING - use sql.string() */
          search_text: SQLStringMarker;
          /** STRING - use sql.string() */
          zip: SQLStringMarker;
          /** STRING - use sql.string() */
          city: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          country_code: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          state_or_region: string;
        }>;
      };
    facility_specialties_in_area: {
        name: "facility_specialties_in_area";
        parameters: {
          /** STRING - use sql.string() */
          zip: SQLStringMarker;
          /** STRING - use sql.string() */
          city: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          country_code: SQLStringMarker;
          /** BOOLEAN - use sql.boolean() */
          filter_has_phone: SQLBooleanMarker;
          /** BOOLEAN - use sql.boolean() */
          filter_has_email: SQLBooleanMarker;
          /** BOOLEAN - use sql.boolean() */
          filter_has_working_website: SQLBooleanMarker;
          /** BOOLEAN - use sql.boolean() */
          filter_has_working_facebook: SQLBooleanMarker;
          /** BOOLEAN - use sql.boolean() */
          filter_has_social: SQLBooleanMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          specialty_canonical: string;
          /** @sqlType STRING */
          specialty_display: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    facility_specialty_regions: {
        name: "facility_specialty_regions";
        parameters: {
          /** STRING - use sql.string() */
          specialty_canonical: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          state_or_region: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    facility_states: {
        name: "facility_states";
        parameters: {
          /** STRING - use sql.string() */
          country_code: SQLStringMarker;
          /** STRING - use sql.string() */
          city: SQLStringMarker;
          /** STRING - use sql.string() */
          zip: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          state: string;
        }>;
      };
    hello_world: {
        name: "hello_world";
        parameters: {
          /** STRING - use sql.string() */
          message: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          value: string;
        }>;
      };
    mocked_sales: {
        name: "mocked_sales";
        parameters: {
          /** INT - use sql.int() */
          max_month_num: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType INT */
          month_num: number;
          /** @sqlType INT */
          revenue: number;
          /** @sqlType INT */
          expenses: number;
          /** @sqlType INT */
          customers: number;
        }>;
      };
    nearest_facility_alternates: {
        name: "nearest_facility_alternates";
        parameters: {
          /** DOUBLE - use sql.double() */
          ref_lat: SQLNumberMarker;
          /** DOUBLE - use sql.double() */
          ref_lon: SQLNumberMarker;
          /** STRING - use sql.string() */
          specialty_canonical: SQLStringMarker;
          /** STRING - use sql.string() */
          claim_search: SQLStringMarker;
          /** STRING - use sql.string() */
          claim_search_2: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          match_type: string;
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          address_city: string;
          /** @sqlType STRING */
          address_state_or_region: string;
          /** @sqlType DOUBLE */
          distance_km: number;
        }>;
      };
  }
}
